//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDelievey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthDeliveryDBEntities : DbContext
    {
        public HealthDeliveryDBEntities()
            : base("name=HealthDeliveryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<h_admin> h_admin { get; set; }
        public virtual DbSet<h_staff> h_staff { get; set; }
        public virtual DbSet<h_customer> h_customer { get; set; }
        public virtual DbSet<h_service> h_service { get; set; }
    }
}
